# Generated by Django 3.0.10 on 2020-10-06 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0003_auto_20201006_1058'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='language',
            options={'verbose_name': 'Язык программирования', 'verbose_name_plural': 'Языки программирования'},
        ),
    ]
