# Generated by Django 3.0.10 on 2020-10-06 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0006_auto_20201006_1121'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Language',
        ),
    ]
